package com.example.rd.baomingxitong.GreenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.rd.baomingxitong.entity.LiaoTian.LTMsg;
import com.example.rd.baomingxitong.entity.LiaoTian.LTXiangmu;

import com.example.rd.baomingxitong.GreenDao.LTMsgDao;
import com.example.rd.baomingxitong.GreenDao.LTXiangmuDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lTMsgDaoConfig;
    private final DaoConfig lTXiangmuDaoConfig;

    private final LTMsgDao lTMsgDao;
    private final LTXiangmuDao lTXiangmuDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lTMsgDaoConfig = daoConfigMap.get(LTMsgDao.class).clone();
        lTMsgDaoConfig.initIdentityScope(type);

        lTXiangmuDaoConfig = daoConfigMap.get(LTXiangmuDao.class).clone();
        lTXiangmuDaoConfig.initIdentityScope(type);

        lTMsgDao = new LTMsgDao(lTMsgDaoConfig, this);
        lTXiangmuDao = new LTXiangmuDao(lTXiangmuDaoConfig, this);

        registerDao(LTMsg.class, lTMsgDao);
        registerDao(LTXiangmu.class, lTXiangmuDao);
    }
    
    public void clear() {
        lTMsgDaoConfig.clearIdentityScope();
        lTXiangmuDaoConfig.clearIdentityScope();
    }

    public LTMsgDao getLTMsgDao() {
        return lTMsgDao;
    }

    public LTXiangmuDao getLTXiangmuDao() {
        return lTXiangmuDao;
    }

}
